
# Пермишены:
#  dynamicinformationboard.command.usage - использование команд плагина
#  dynamicinformationboard.command.reload - использование аргумента reload

# Боарды, можно создавать сколько угодно
boards:
  board1:
    # Обновление боарда, в секундах, установите 0, чтобы отключить
    update-delay: 180
    # Путь до картинки, которая будет использоваться для фона
    image: "image.png"
    # Размер боарда по высоте
    height-dimension: 5
    # Размер боарда по ширине
    width-dimension: 5
    # Цвет фона, формат r;g;b, например: 0;0;0 - черный, 255;255;255 - белый
    # Укажите none, чтобы сделать фон прозрачным
    background-color: "0;0;0"
    # Делает рамки невидимыми
    frame-invisibly: true
    # Направление боарда, доступные направления: NORTH, EAST, SOUTH, WEST
    board-face: WEST
    # Дистанция, в которой боард будет отображаться для игрока
    distance-view: 20
    # Локация боарда
    location:
      world: world
      x: 0
      y: 90
      z: 0
    # Строки, которые будут добавляться к фону, можно создавать сколько угодно
    strings:
      string1:
        # Путь до шрифта, если указан неверно, используется по умолчанию
        font: ""
        # Размер шрифта
        size: 30
        # Текст, который будет выведен
        text: "%placeholder%"
        # Позиция строки, отсчёт от левого верхнего угла, в пикселях
        offset-x: 100
        # Позиция строки, отсчёт от левого верхнего угла, в пикселях
        offset-y: 100
        # Цвет текста, формат r;g;b, например: 0;0;0 - черный, 255;255;255 - белый
        color: "0;0;0"

# Оставьте пустым, чтобы сообщения не отправлялось
messages:
  no-permission: "&cНедостаточно прав для использования этой команды!"
  command-help-header: "Помощь по командам:"
  command-reload-help: "/dynamicinformationboard reload - Перезагрузка плагина"
  command-reload-confirm: "&aПлагин успешно перезагружен! &7(%msms)"
